### ISSUE TITLE
Infinite scroll along the time axis

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1114]
- [ ] autoGrowTimeAxis config on Scheduler, reacting to ScrollManager reaching end or start point of the timeaxis (on by default for resize, drag drop, drag create interactions)
- [ ] Scrolling will use sliding window approach
- [ ] A demo showing incremental load as you scroll along the time axis
- [ ] Configurable buffer window size (bufferCoef in Ext Scheduler)?

https://www.bryntum.com/forum/viewtopic.php?p=74185#p74185
https://www.bryntum.com/forum/viewtopic.php?p=73065#p73065
https://www.bryntum.com/forum/viewtopic.php?p=69153#p69153
https://www.bryntum.com/forum/viewtopic.php?p=63455#p63455
https://www.bryntum.com/forum/viewtopic.php?p=62135#p62135
https://www.bryntum.com/forum/viewtopic.php?p=74578#p74578

**Comment by bmblb** [comment]
Requested here too: https://www.bryntum.com/forum/viewtopic.php?f=44&t=14907

**Comment by svmx-abhaydesai** [comment]
We are also in need of this feature, can you please share any latest updates?

**Comment by kynak** [comment]
hello, we are also interested in this feature as well

- auditboard (sub'd to gantt & scheduler pro)

**Comment by matsbryntse** [comment]
Progress:
https://user-images.githubusercontent.com/218570/110935051-302eb100-832f-11eb-80f5-a9076c65719e.mp4

**Comment by li-dennis** [comment]
Is this issue resolved in the sense that new versions of bryntum now support it?

**Comment by aamcatamney** [comment]
Are there any examples of lazy loading?  
Specifically looking at the grid

**Comment by bmblb** [comment]
@aamcatamney What do you want to lazy load? You mention grid, but grid does not support infinite scrolling. Only timelines (scheduler, gantt) do. When you scroll timeline, you can listen to reconfigure event to know when new time span was rendered: https://bryntum.com/docs/gantt/api/Scheduler/data/TimeAxis#event-reconfigure

**Comment by bmblb** [comment]
@aamcatamney This pull request is unrelated to your problem. Normally we do not take reports and questions on github. Please ask this question on the [forum](http://forum.bryntum.com/). But search first, this question might have been asked already.
