### ISSUE TITLE
Calendar Component 1.0

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#179]
1.0

Views:
- [x] Month
- [x] Day
- [x] Week
- [x] Agenda
- [x] Year
- [x] Calendar aggregation of views.

Drag feature
- [x] Drag to create (#472)
- [x] Drag drop (#473)
- [x] Resize (#474)

Interaction
- [x] Double click (or configurable gesture) to create (#475)
- [x] Task tooltip (#476)

Misc:
- [ ] Styling https://github.com/bryntum/support/issues/926
- [ ] Bug bash https://github.com/bryntum/support/issues/925
- [ ] Test coverage https://github.com/bryntum/support/issues/924
- [x] Readonly mode (https://github.com/bryntum/bryntum-suite/issues/1369)
- [x] Responsiveness (update overflow count as height is changed)
- [x] DayView startHour/endHour
- [ ] Themes (#477)
- [x] Event editor (reuse Scheduler) (#478)
- [x] Recurring events (#479)
- [x] Examples
- [ ] Localization (#480)
- [x] Tests
- [x] Docs (#481)
- [ ] Intro blog post (#482)
- [ ] Web site pages (#483)
- [x] Build scripts (#484)
- [x] Mini example for examples browser intro section

**Year view**
- [x] Aggregating view should show current year (#485)
- [x] Indicator for current day, circle (#486)

Examples:
- [x] EventEdit customization
- [x] Demo of filter, like https://www.bryntum.com/examples/scheduler/filtering/
- [ ] Custom styling / event rendering / coloring of bars, background cell styling
- [x] custom tooltip demo
- [x] live demos for features in docs

**Comment by matsbryntse** [comment]
Split into sub-tickets
