### ISSUE TITLE
TaskBoard todo

### ISSUE THREAD

**Issue by isglass** [bryntum/support#2270]
- [x] Swimlane column with details (in demo)
- [x] Column header with task count
- [x] Collapse expand column
- [x] Collapse expand swimlane
- [x] Zoom
- [x] Cards does not need to fill width
- [x] Column picker
- [x] Swimlane picker
- [x] Horizontal scroll with many columns
- [x] Drag columns
- [x] Add button per cell
- [x] Avatars
- [x] Tooltips
- [x] Editor
- [x] - Resources
- [x] - Column
- [x] - Swimlane
- [x] Consume project
- [x] Themes
- [ ] Locales
- [x] Swimlane config, set height

**Demos**
- [ ] Combo demo with Scheduler or Gantt / Grid. https://bryntum.com/examples/taskboard-for-extjs/scheduler/
- [x] With "Group by" combo box allowing dynamic grouping
- [x] Demo with filtering
- [x] Demo with config panel

From #249, for the future 
- Configurable validator to easily define where a task can be dropped
- Dependencies between tasks (reuse from scheduler)

**Comment by isglass** [comment]
Remaining tasks turned into separate tickets
