### ISSUE TITLE
Task Board component

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#249]
- [ ] Configurable columns
- [ ] Drag drop
- [ ] Configurable validator to easily define where a task can be dropped
- [ ] Localization
- [ ] Examples
- [ ] Docs
- [ ] Tests
- [ ] Themes
- [ ] Reorderable columns with drag drop
- [ ] Swimlanes
- [ ] Dependencies between tasks (reuse from scheduler)

![image](https://user-images.githubusercontent.com/218570/73521141-8d0a2900-4405-11ea-93f4-cf98cad0f9f3.png)

**Comment by isglass** [comment]
Closed in favor of #2270
