### ISSUE TITLE
Todo for 5.0 

### ISSUE THREAD

**Issue by isglass** [bryntum/support#3527]
Bigger tasks:

- [x] https://github.com/bryntum/support/issues/3276 - Sergey / Johan
- [ ] https://github.com/bryntum/support/issues/2805 - Sergey / Johan
- [x] https://github.com/bryntum/support/issues/1265 - Arcady
- [ ] https://github.com/bryntum/support/issues/2786 - Sergey / Saki
- [ ] https://github.com/bryntum/support/issues/2787 - Sergey / Saki
