### ISSUE TITLE
RTL Support: Scheduler

### ISSUE THREAD

**Issue by isglass** [bryntum/support#3540]
Branch `scheduler-rtl`

Check:

- [ ] Date mapping
- [ ] Event rendering, horizontal mode
- [ ] Event rendering, vertical mode
- [ ] Event navigation, horizontal mode
- [ ] Event navigation, vertical mode
- [ ] Scrolling, horizontal mode
- [ ] Scrolling, vertical mode
- [ ] ResourceCollapseColumn
- [ ] ResourceInfoColumn
- [ ] ColumnLines
- [ ] Dependencies
- [ ] DependencyEdit
- [ ] EventContextMenu
- [ ] EventCopyPaste
- [ ] EventDrag
- [ ] EventDragCreate
- [ ] EventDragSelect
- [ ] EventEdit
- [ ] EventFilter
- [ ] EventMenu
- [ ] EventResize
- [ ] EventTooltip
- [ ] GroupSummary
- [ ] HeaderZoom
- [ ] Labels
- [ ] NonWorkingTime
- [ ] Pan
- [ ] ResourceTimeRanges
- [ ] ScheduleContext
- [ ] ScheduleMenu
- [ ] ScheduleTooltip
- [ ] SimpleEventEdit
- [ ] StickyEvents
- [ ] Summary
- [ ] TimeAxisHeaderMenu
- [ ] TimeRanges
- [ ] ProjectCombo
- [ ] ResourceCombo
- [ ] ResourceFilter
- [ ] UndoRedo
