### ISSUE TITLE
Live updates support

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#6226]
There is a new API allowing to sync changes between projects - `applyProjectChanges` which is used to update app via Websocket messages. However, this API breaks the base assumption components were built on leading to multiple problems. Therefore, UI and data layer should be updated to work properly with this new API.

Check this PR for detailed explanation with diagrams depicting workflows: https://github.com/bryntum/bryntum-suite/pull/6638

Related issues:

- [x] implement a queue for incoming changes for a time local queue is paused to apply them later in bulk #7223
- [x] setRangeEnd exception when replacing id early #7770 
- [x] WBS trees get out of sync when two clients send changes simultaneously #7784 
- [x] projects get out of sync when one client moves task and another resizes it #7801 
- [x] constraint removed on paste #7858 
- [x] CellEdit behaves incorrectly on double click #7869
- [x] Undo deleting dependency is broken #7955
- [x] `addTask` method should use queue too #8008 
- [x] Add public websocket demo #2012
- [x] Applied duration is ignored #7993

**Comment by bmblb** [comment]
Real life usage of live updates exposed several more issues not solved in this PR. Queue does solve the problem of providing safe windows to apply changes to local project. However, there are some cases related to project lifecycle and user actions.

## Figuring out what constitutes a change

### History

When first CRUD manager was implemented in ExtGantt, there was a couple of configs to sync automatically and a timer which defined interval between change observation and sync request. Reason was to avoid spamming with requests on every single change and instead wait a little hoping to group all changes into one larger changeset.

From that point on API was improved, new features added, data package was refactored, asynchronous processes started to appear. CRUD API did not change, because it successfully handled changes using a timeout approach.

### Problem

In ExtGantt we could use synchronous events to tell when all changes were applied to store and project was calculated. When ProjectModel appeared, project calculation became asynchronous. There is an event which marks end of calculation, however not every change starts project calculation. Modifying task or resource names constitutes a change, but project will not calculate. One can tell there are two channels for changes - project-related, and project-unrelated. And problem is that there is no easy way to tell when it is safe to persist changes.

Queue implementation brought some control over local changes and remote changes concurrency, e.g. if user is actively using UI feature his work won't be interrupted by sudden change of the underlying data. But there is still a time window at which remote changes can interrupt local state. That is a window after queue has finished, but changes are not yet synced to the backend because we're waiting for a timeout. (btw, why wait for timeout? maybe save on tansactional feature to trigger finalize event?)

### Proposed solution

To solve this problem, we need to eliminate this fragile project state when queue is empty, project has some changes and is waiting for a timeout to send those changes to the backend.

## Meta-feature behavior

If user is spamming Enter key to add multiple tasks that can be considered a single transaction. We don't want (probably) to send message for each new task. We want to send one when editing is finished. Queue cannot possibly do that, because it isolates individual cell edits.
