### ISSUE TITLE
New CSS variable based themes

### ISSUE THREAD

**Issue by isglass** [bryntum/support#7807]
3 new themes are currently planned, with a light and dark version of each:

- Material3, which will as far as possible follow materials spec for v3 (Material3Light, Material3Dark)
- Stockholm, which will look somewhat similar to the current theme (StockholmLight, StockholmDark)
- Svalbard, which will be a minimalistic theme (SvalbardLight, SvalbardDark)
- Possibly one more

EDIT: Made 4, added "Visby" too

Each widget, feature etc. (Bryntum entity below) will import its own CSS (using import attributes, which currently only works in Chrome & probably Edge). This will enable "minimal" builds of themes. We will also supply pre-built "full" themes + thin CSS bundles similar to today.

CSS nesting will be used + `color-mix` or relative colors (color-mix has some performance issues, but relative colors is very new) to use variations of a primary color or a neutral color throughout. The primary color can be specified globally but overridden per element.

Each Bryntum entity will use CSS variables (custom properties) for the parts of their styling that we think will be relevant to adjust in different themes. Mainly colors, font-size, borders, paddings etc. The "fixed" parts will be plain CSS. CSS variables that share value in most themes will have a default value, to keep the themes thinner.

Each theme will only contain CSS variable assignments.

A new `rendition` concept will be introduced. Currently Buttons & Textfields (and similar fields) support it. Text fields has two renditions: "outlined" & "filled", matching what Material 3 offers. Buttons have more (also matching Material 3): "outlined", "tonal", "filled", "elevated" & "text". `rendition` can also be specified on a container, which applies it to any item that does not specify a rendition directly.

Todo:

- [ ] Check button contrast in all themes & renditions
- [x] Normalize xx-background & xx-background-color
- [x] Rename themes to lowercase
- [x] Revisit Mouseable for ripples etc
- [x] Reconsider --b-parent-background, see todo in code
- [x] Try fieldset + legend for outlined textfields border (seems not worth it)
- [x] New things to style
    - [x] Tab close 
    - [x] Tab reorder
    - [x] S-curve
    - [x] TickCells
    - [x] TreeSummary
    - [x] Docs browser
    - [x] Drawer
    - [x] RowEdit
    - [x] DayView transitions
    - [x] Split button
    - [x] Calendar tickRenderer
    - [x] Single assignment resource combo in TaskBoard
    - [x] New HintFlow mask
    - [x] ChecklistFilterCombo
    - [x] Updated ScrollButtons feature
    - [x] Updated maps demo
    - [x] Charts
    - [x] Card collapse  
    - [x] Max Ripple changes
    - [x] MonthGrid
    - [x] column-search
    - [x] Splitter buttons
- [ ] Custom theme demos
    - [x] Grid
    - [x] Scheduler
    - [ ] SchedulerPro
    - [x] Gantt
    - [x] Calendar
    - [x] TaskBoard
- [x] Test for:
    - [x] New transition system
    - [x] Renditions
    - [x] Slider label, steps
    - [x] DomSync beforeRemove
    - [x] Grid row removal / insertion
    - [x] Grid column collapse / expand
    - [x] Grid column show / hide
    - [x] Grid group collapse / expand
    - [x] Scheduler row removal / insertion
    - [x] Scheduler group collapse / expand
    - [x] Scheduler tree expand / collapse
    - [x] Scheduler vertical mode event removal / insertion  
    - [x] Gantt tree expand / collapse
    - [x] Gantt row removal / insertion
    - [x] Plain / rich tooltips
    - [x] Outlined field label background in material (parentBackgroundColor detection)
    - [x] Event resize handle transition

- [x] Add CSS var docs:
    - [x] Core
    - [x] Grid
    - [x] Scheduler
    - [x] SchedulerPro
    - [x] Gantt
    - [x] Calendar
    - [x] TaskBoard

- [x] Update framework demo styling  

- [x]  Deprecate:
   - [x] animateRemovingRows
   - [x] animateCollapseExpand
   - [x] animateTreeNodeToggle
   - [x] enableEventAnimations

- [ ] Address color-mix performance issues (flight dispatch demo). Either mix on event level, reduce shades, or try relative color syntax instead (very new though)

- [x] Migration guide
- [ ] Update all guides & docs
    - [ ] Check all fiddles
    - [ ] New custom structural CSS from sources guide (can come after 7.0)

- [x] Make it easy to apply border-radius to panels, with or without headers, should end up correctly
- [x] Make new light theme that is very light
- [x] Make sure list checkboxes does not have transparent check marks
- [x] List with checkbox should have symmetrical selection padding
- [x] Hollow buttons
- [ ] https://github.com/bryntum/support/issues/7840
- [ ] A single variable for grid+header padding
- [ ] Ability to add horizontal "margin" spacing between grid cells 
- [x] All themeable values to be imported as CSS properties
- [ ] Add easy way to assign colors to icons "b-fa b-fa-triangle-exlcamation b-red" or similar
- [x] Remove header background color of Popup/Tooltip in Calendar (compare scheduler "tooltips" demo)
- [x] Remove bg-color for check-column cells

A list of our defined colours should be injected into the CSS so as to be detectable in code:

```
---bryntum-colors : "red#ff8787,pink#f783ac";
```

Then to detect whether a string is a CSS literal, we can interrogate our colour list.

```
// Only pluck this once. Convert to an object which maps names to color literals
const colorDefinitions = getComputedStyle(element).getPropertyValue('--bryntum-colors').split(',');
```

Also, that would allow an `EventColorPicker` to populate its own store from the CSS instead of hard coding its colours.

**Comment by ExtAnimal** [comment]
See also https://github.com/bryntum/support/issues/574

**Comment by ExtAnimal** [comment]
we should make the `.float-root` use

```
display : grid; 
place-items : center;
```

And then have `.b-centered` use

```
position : static;
align-self : auto;
```

That way, they would just be centered by layout, without that `top : 50%; left : 50%; transform : translate(-50%, -50%);` hack. No visible difference, just cleaner modern CSS.

**Comment by chuckn0rris** [comment]
Requested themeable vals here https://forum.bryntum.com/viewtopic.php?f=51&t=28168&p=141563#p141563

**Comment by isglass** [comment]
Comment re. future Salesforce compatibility from the Bryntum Experts channel:

Recently Salesforce has announced an upgrade to their user interface, named Enhanced Lightning UI (ELUI). It will become generally available in the Summer 2025 release and will be entirely based on CSS custom properties that they call “[styling hooks](https://www.lightningdesignsystem.com/platforms/lightning/styling-hooks/)”.
There are two kinds of styling hooks: global and component-level. Global styling hooks are defined at the page level and set the general theme: background, foreground, border and accent colours, spacing and sizing, shadows, etc. Component-level hooks are used in component Shadow DOM and allow additional customisation. Component’s stylesheet uses the internal CSS properties with a global CSS property fallback: border-radius: var(--slds-c-badge-radius-border, var(radius-border-pill)) so that it defaults to a global value which can be overridden for this individual component if necessary.
To make use of those “styling hooks” in our custom theme, we’d like to request some changes to your base (default) theme. Currently it heavily relies on SASS transformations and computations: adjusting colour opacity, mixing colours, concatenating spacings, etc. Many, if not all, of those calculations are now supported natively in CSS. Using CSS functions would permit us to use CSS custom properties as values, rather than have them “baked” into the theme. By switching to CSS properties we can hook onto those global styling hooks (pun intended) and get the all the benefits of the new enhanced UI (including automatic switching to night/dark mode).
We have already made some changes to support some of the global hooks by overriding a few SASS functions with custom CSS-friendly implementations:

```
@function transparentize($color, $amount) {
  @if $color == transparent {
    @return $color;
  }

  @return unquote("rgb(from #{$color} r g b / calc(alpha - #{$amount}))");
}
```

But this is not enough and more is needed. There are some functions that we could not override because their results were being used in SASS for compile-time decision making. For example, in toolbar.scss:

```
$separator-start-color : null !default;
$separator-end-color   : null !default;

@if lightness($panel-toolbar-background-color) > lightness($panel-toolbar-color) {
    // Light background theme
    $separator-start-color : darken($panel-toolbar-background-color, 10%);
    $separator-end-color   : darken($panel-toolbar-background-color, 5%)
} @else {
    // dark background theme
    $separator-start-color : lighten($panel-toolbar-background-color, 20%);
    $separator-end-color   : lighten($panel-toolbar-background-color, 10%);
}
```

So the number one thing that could help us in this effort is refactoring all SASS computations in the base theme into CSS functions. We were considering doing this ourselves but decided not to commit to it as to avoid having to make constant adjustments with every new version you release.
The next thing that could help us would be implementing something like Salesforce’s “component-level styling hooks” for all widgets. Currently the TaskBoard is very close to being that but a few things could be improved. For example, the b-taskboardbase class defines its own CSS properties rather than rely on fallback values. This sometimes requires us to use higher specificity selectors to override the defaults rather than simply define them in our theme.
The last thing would be ensuring that all aspects of the UI are customisable and hard-coded values are only used where customisation is not expected. Currently there are a lot of hard-coded spacings, colours, font sizes, etc.
One idea I’d like to share with you here is theme namespaces. Rather than defining theme CSS properties at the page level using :root or similar selector, create a theme-specific CSS class. For example, b-theme-stockholm, and declare all CSS properties within.
Take a simple widget like a chipview. Its CSS might look something like this:
```
.b-chip {
    display          : flex;
    align-items      : center;
    padding-block    : var(--b-chip-padding-block);
    padding-inline   : var(--b-chip-padding-inline);
    border-radius    : var(--b-chip-border-radius);
    background-color : var(--b-chip-color-background);
    color            : var(--b-chip-color);
    transition       : background-color .3s, color .3s;
}
```
And the theme entry for it could be:
```
.b-theme-stockholm {
    --b-chip-padding-block: .3em;
    --b-chip-padding-inline: .7em;
    --b-chip-border-radius: 1em;
    --b-chip-background-color: var(--b-theme-color-light-gray);
    --b-chip-color: lab(from var(--b-widget-color-text-dark) calc(l + 5) a b);
}
```
This would allow easier theme switching by loading all theme stylesheets at once and simply applying different theme class to the host element. One could even render two components side-by-side using different themes for comparison!
The benefit for us here is that we’d simply define our own theme class b-theme-salesforce or something that would use “global styling hooks” rather than hard-coded colour or unit values:
```
.b-theme-salesforce {
    --b-chip-padding-block: var(--slds-g-spacing-1);
    --b-chip-padding-inline: var(slds-g-spacing-2);
    --b-chip-border-radius: var(--slds-g-radius-border-pill);
    --b-chip-background-color: var(--slds-g-color-surface-container-1);
    --b-chip-color: var(--slds-g-color-on-surface-3);
}
```
Is there anything like this on your roadmap? Would you consider a staged approach where more basic features (like SASS → CSS function transition) could be delivered sooner than the rest?

**Comment by matsbryntse** [comment]
Misaligned checkbox "labels" http://lh/bryntum-suite/Grid/examples/fieldfilters/

<img width="519" alt="Image" src="https://github.com/user-attachments/assets/35b02bca-9542-46c3-92e5-6a36741400b6" />

**Comment by isglass** [comment]
ButtonGroup rendition

![Image](https://github.com/user-attachments/assets/bf18c9e5-5049-42d6-bc69-8da004b2c403)

**Comment by isglass** [comment]
https://github.com/bryntum/support/issues/574
